### ISSUE TITLE
customTitle

### ISSUE THREAD

**Issue by Doudy** [SpoturDeal/MMM-Domoticz#14]
Hello,
In the previous version there was possibility to adapt the customTitle.
Is it possible to adapt in this version?
I have for example 'WH2600-Indoor' and I would like to put 'Living'.
In this version you take the 'Name' of the idx in Domoticz!

**Comment by SpoturDeal** [comment]
Read the Full manual. 

_In the previous version there was possibility to adapt the customTitle._
_Is it possible to adapt in this version?_

|Option|Description|
|---|---|
moduleTitle | Defines the headline text.Type: stringDefault: My smart home by Domoticz
-- | --

This is and was always the Title option
_In this version you take the 'Name' of the idx in Domoticz!_
**Nothing has been changed here since the module was made**

**Comment by Doudy** [comment]
In previous version i have:
`
{
						idx: "39", //WH2600-Indoor
`
`						symbolon: "fas fa-temperature-high",`
`						symboloff: "fas fa-temperature-high",`
`						customTitle: "Living", },`

**Comment by SpoturDeal** [comment]
Where did you obtain that part of code.

there were never the options `symbolon, symboloff, customTitle` they are also not from the JSON from your domoticz

```
http://192.168.xxx.xxx:8088/json.htm?type=devices&used=true&filter=all
```
Check this in your browser replace xxx with the numbers from your Domoticz

I hope your are not mixing up different modules for the MagicMirror

**Comment by Doudy** [comment]
Excuse me it was a different module:
[https://github.com/M-Arvidsson/MMM-domoticz](url)

**Comment by SpoturDeal** [comment]
This is already your second time.
